"""create the groups table

Revision ID: be0ac635c8ae
Revises: 0f0bb6353804
Create Date: 2020-11-24 16:19:51.151139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0ac635c8ae'
down_revision = '0f0bb6353804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('class_id', sa.Integer(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column('created_on', sa.DateTime,
                              server_default=sa.func.now()),
                    sa.Column(
                        'updated_on',
                        sa.DateTime,
                        server_default=sa.func.now(),
                        server_onupdate=sa.func.now()
                    )
                    )
    op.create_table('group_students',
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('student_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
                    sa.Column('created_on', sa.DateTime,
                              server_default=sa.func.now()),
                    sa.Column(
                        'updated_on',
                        sa.DateTime,
                        server_default=sa.func.now(),
                        server_onupdate=sa.func.now()
                    )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_students')
    op.drop_table('groups')
    # ### end Alembic commands ###
