"""create the roles table

Revision ID: 15da86fd3e8f
Revises: 
Create Date: 2020-11-23 19:17:46.818703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15da86fd3e8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
