"""create the classroom table

Revision ID: e10ccf738b56
Revises: 56730ac79e8f
Create Date: 2020-11-24 16:08:57.535206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10ccf738b56'
down_revision = '56730ac79e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('class_image_url', sa.Text(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('daily_objective', sa.Text(), nullable=True),
                    sa.Column('meeting_link', sa.String(
                        length=255), nullable=True),
                    sa.Column('meeting_pw', sa.String(
                        length=255), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column('created_on', sa.DateTime,
                              server_default=sa.func.now()),
                    sa.Column(
                        'updated_on',
                        sa.DateTime,
                        server_default=sa.func.now(),
                        server_onupdate=sa.func.now()
                    )
                    )
    op.create_table('classroom_user',
                    sa.Column('class_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.Column('created_on', sa.DateTime,
                              server_default=sa.func.now()),
                    sa.Column(
                        'updated_on',
                        sa.DateTime,
                        server_default=sa.func.now(),
                        server_onupdate=sa.func.now()
                    )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom_user')
    op.drop_table('classes')
    # ### end Alembic commands ###
