"""create questions table

Revision ID: 549ca3ee2095
Revises: e10ccf738b56
Create Date: 2020-11-24 16:15:51.606776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549ca3ee2095'
down_revision = 'e10ccf738b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('image_url', sa.Text(), nullable=True),
                    sa.Column('student_id', sa.Integer(), nullable=True),
                    sa.Column('instructor_id', sa.Integer(), nullable=True),
                    sa.Column('class_id', sa.Integer(), nullable=True),
                    sa.Column('resolved', sa.Boolean(), nullable=True),
                    sa.Column('created_on', sa.DateTime,
                              server_default=sa.func.now()),
                    sa.Column(
                        'updated_on',
                        sa.DateTime,
                        server_default=sa.func.now(),
                        server_onupdate=sa.func.now()
                    ),
                    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
                    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
