"""create the users table

Revision ID: 56730ac79e8f
Revises: 
Create Date: 2020-11-24 16:06:12.474136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56730ac79e8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=40), nullable=True),
                    sa.Column('first_name', sa.String(
                        length=40), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=40), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('avatar_url', sa.Text(), nullable=True),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('role', sa.String(length=50), nullable=False),
                    sa.Column('created_on', sa.DateTime,
                              server_default=sa.func.now()),
                    sa.Column(
                        'updated_on',
                        sa.DateTime,
                        server_default=sa.func.now(),
                        server_onupdate=sa.func.now()
                    ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
