"""create answers table

Revision ID: 0f0bb6353804
Revises: 549ca3ee2095
Create Date: 2020-11-24 16:18:30.099886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0bb6353804'
down_revision = '549ca3ee2095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=True),
                    sa.Column('instructor_id', sa.Integer(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['question_id'], ['questions.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column('created_on', sa.DateTime,
                              server_default=sa.func.now()),
                    sa.Column(
                        'updated_on',
                        sa.DateTime,
                        server_default=sa.func.now(),
                        server_onupdate=sa.func.now()
                    )

                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    # ### end Alembic commands ###
